version: "3.7"

services:
  fe:
   container_name: fe
   build:
     context: .
     dockerfile: dockerfile.fe
   ports:
     - "3000"
  be:
    container_name: be
    build:
      context: .
      dockerfile: dockerfile.be
    ports:
      - "9000:9000"
    restart: on-failure
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure
    ports:
      - "80:80"
      